- FrontEnd/my-car/src/common/Alert.js
> [feat] 최상단 공통 컴포넌트 구현

- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/mycar/Mycar.js
- FrontEnd/my-car/src/mycar/components/Footer.js
- FrontEnd/my-car/src/mycar/components/SummaryModal.js
견적요약보기 클릭시 모달 뜨고, x 누르면 모달 없어짐
[issue] #8
> [feat] 내차만들기/footer/견적요약보기 모달창

- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/mycar/Mycar.js
우측 상단 아카이빙 버튼 누를 시 Alert 뜨고, 취소 누를 시 Alert 삭제
[issue] #3
> [feat] 최상단 alert 액션 구현

- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/components/ImgSelect.js
- FrontEnd/my-car/src/mycar/routers/BodyType.js
- FrontEnd/my-car/src/mycar/routers/Engine.js
왼쪽 이미지 컴포넌트 뷰 & 액션까지 구현 완료
[issue] #10
> [feat] 내차만들기/바디타입 왼쪽 이미지 컴포넌트

- FrontEnd/my-car/src/mycar/components/OptChangeBtn.js
- FrontEnd/my-car/src/mycar/components/SummaryModal.js
견적요약보기 모달-옵션변경 버튼 생성
[issue] #8
> [feat] 옵션 변경 버튼 생성

- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
- FrontEnd/my-car/src/router.js
> [feat] 내차만들기 완성 라우터 설정

- FrontEnd/my-car/src/mycar/components/OptionCard.js
선택옵션카드의 상태에 따른   추가&취소 버튼 style 변경
[issue] #13
> [style] 내차만들기-선택옵션 추가&취소 버튼

- FrontEnd/my-car/src/mycar/components/OptionCard.js
- FrontEnd/my-car/src/mycar/routers/SelectOption.js
선택옵션 취소시 userCar 상태에서 remove
[issue] #13
> [feat] 내차만들기/선택옵션 취소하기

- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/components/CompletedFunction.js
- FrontEnd/my-car/src/mycar/components/NavBar.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
- FrontEnd/my-car/src/router.js
내차만들기-완성페이지 내 기능요약배너 구현
[issue] #14
> [feat] 완성페이지 기능요약배너 구현

- FrontEnd/my-car/src/mycar/components/CompletedFunction.js
> [refactor] 완성페이지

- FrontEnd/my-car/src/mycar/Mycar.js
- FrontEnd/my-car/src/mycar/components/Footer.js
- FrontEnd/my-car/src/mycar/components/MandatoryCard.js
- FrontEnd/my-car/src/mycar/components/TrimCard.js
- FrontEnd/my-car/src/mycar/routers/BodyType.js
- FrontEnd/my-car/src/mycar/routers/Color.js
- FrontEnd/my-car/src/mycar/routers/Engine.js
- FrontEnd/my-car/src/mycar/routers/WheelDrive.js
- FrontEnd/my-car/src/mycar/util/SelectedIndex.js
userCar 객체에 인덱스 0 옵션으로 미리 저장하지 않고 각 페이지에서 useEffect를 사용하여 디폴트 옵션 넣어줌 [issue] #68
> [fix] setUserCar 관련 푸터 이슈 해결

- FrontEnd/my-car/src/mycar/components/ToolTip.js
> [feat] 내차만들기 완성페이지 툴팁 제거

- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/mycar/components/CompleteTopBanner.js
- FrontEnd/my-car/src/mycar/components/CompletedFunction.js
- FrontEnd/my-car/src/mycar/components/Footer.js
- FrontEnd/my-car/src/mycar/components/NavBar.js
- FrontEnd/my-car/src/mycar/components/OptionCard.js
- FrontEnd/my-car/src/mycar/components/SelectedOption.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
선택옵션 0 일때 문구, 여러개일때 스크롤
[issue] #14
> [feat]완성페이지 선택옵션 구현

- FrontEnd/my-car/src/mycar/components/AddProcessBtn.js
- FrontEnd/my-car/src/mycar/components/CompletedFunction.js
- FrontEnd/my-car/src/mycar/components/SelectedOption.js
추가절차 컴포넌트 구현으로 인한 내차만들기 완성페이지 완성
[issue] #14
> [feat]내차만들기완성페이지 추가절차 과정 구현

- FrontEnd/my-car/src/mycar/routers/SelectOption.js
> [feat] 선택옵션 위치보기 플립카드구현

- FrontEnd/my-car/src/api.js
- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/routers/BodyType.js
- FrontEnd/my-car/src/mycar/routers/Color.js
- FrontEnd/my-car/src/mycar/routers/Engine.js
- FrontEnd/my-car/src/mycar/routers/Model.js
- FrontEnd/my-car/src/mycar/routers/SelectOption.js
- FrontEnd/my-car/src/mycar/routers/WheelDrive.js
- FrontEnd/my-car/src/mycar/routers/parents/RootColor.js
- FrontEnd/my-car/src/mycar/routers/parents/RootSelectOption.js
- FrontEnd/my-car/src/mycar/routers/parents/RootTrims.js
- FrontEnd/my-car/src/router.js
> [feat] 내차만들기 기본 API 구조 설정

- FrontEnd/my-car/src/mycar/components/AnimationMovingCar.js
- FrontEnd/my-car/src/mycar/components/CompleteTopBanner.js
- FrontEnd/my-car/src/mycar/components/SummaryModal.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
내차만들기-완성페이지 애니메이션 구현
[feat] #80
> [feat]내차만들기 완성페이지 애니메이션 구현

- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/archiving/Achiving.js
- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/main/Main.js
- FrontEnd/my-car/src/mycar/components/CompleteTopBanner.js
- FrontEnd/my-car/src/mychiving/Mychiving.js
- FrontEnd/my-car/src/router.js
각 버튼 클릭 시 해당하는 페이지로 이동
[issue] #93
> [feat]페이지 라우팅

- FrontEnd/my-car/src/api.js
- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/Mycar.js
- FrontEnd/my-car/src/mycar/components/BasicOptionModal.js
- FrontEnd/my-car/src/mycar/components/DetailExplainCard.js
- FrontEnd/my-car/src/mycar/components/Footer.js
- FrontEnd/my-car/src/mycar/components/MandatoryCard.js
- FrontEnd/my-car/src/mycar/components/OptionCard.js
- FrontEnd/my-car/src/mycar/components/OptionTabs.js
- FrontEnd/my-car/src/mycar/components/TitlePriceTag.js
- FrontEnd/my-car/src/mycar/components/TrimCard.js
- FrontEnd/my-car/src/mycar/components/TrimImg.js
- FrontEnd/my-car/src/mycar/components/TrimModelImg.js
- FrontEnd/my-car/src/mycar/routers/BodyType.js
- FrontEnd/my-car/src/mycar/routers/Color.js
- FrontEnd/my-car/src/mycar/routers/Engine.js
- FrontEnd/my-car/src/mycar/routers/Model.js
- FrontEnd/my-car/src/mycar/routers/SelectOption.js
- FrontEnd/my-car/src/mycar/routers/WheelDrive.js
- FrontEnd/my-car/src/mycar/routers/parents/RootColor.js
- FrontEnd/my-car/src/mycar/routers/parents/RootSelectOption.js
- FrontEnd/my-car/src/mycar/useSelect.js
- FrontEnd/my-car/src/router.js
내차만들기 트림/모델 -> 선택옵션 N Peerfomance 까지 서버에서 받은 옵션 데이터로 구성 및 선택옵션 스타일 일부 변경 
[issue] #81
> [feat] 내차만들기 데이터 패치 및 뷰에 적용

- FrontEnd/my-car/src/main/components/ToArchiving.js
- FrontEnd/my-car/src/main/components/ToMycar.js
- FrontEnd/my-car/src/main/components/ToMychiving.js
> [feat]버튼 클릭 포인트 크기 조절

- FrontEnd/my-car/src/mycar/components/SummaryModal.js
가격 toLocaleString 적용 및 색상 부분 뷰 변경
[issue] #100
> [feat] 내차만들기/견적요약모달 수정

- FrontEnd/my-car/src/mycar/components/CompletedFunction.js
- FrontEnd/my-car/src/mycar/components/OptionCard.js
- FrontEnd/my-car/src/mycar/components/SelectedOption.js
유저가 선택한 색상 및 선택 옵션 이미지를 src를 설정하고 일부 스타일을 변경
[issue] #87
> [feat] 내차만들기/완성페이지

- FrontEnd/my-car/src/main/Main.js
- FrontEnd/my-car/src/main/components/MainHeader.js
- FrontEnd/my-car/src/main/components/ToArchiving.js
- FrontEnd/my-car/src/main/components/ToMycar.js
- FrontEnd/my-car/src/main/components/ToMychiving.js
> [feat]메인페이지 비디오 배경화면 설정

- FrontEnd/my-car/src/mycar/components/DetailExplainCard.js
- FrontEnd/my-car/src/mycar/routers/SelectOption.js
패키지가 아닌 선택 옵션의 경우 옵션 위치보기 버튼을 클릭하면 해당 옵션 위치가 차 이미지에 포인팅 [issue] #13
> [feat] 내차만들기/옵션 위치보기(선택옵션)

- FrontEnd/my-car/src/main/Main.js
- FrontEnd/my-car/src/main/components/Pagination.js
> [feat]페이지네이션 추가

- FrontEnd/my-car/src/main/Main.js
- FrontEnd/my-car/src/main/components/Pagination.js
- FrontEnd/my-car/src/main/components/ToArchiving.js
- FrontEnd/my-car/src/main/components/ToMycar.js
- FrontEnd/my-car/src/main/components/ToMychiving.js
페이지네이션 이동 및 transition 구현
[issue] #95
> [feat]메인페이지-페이지네이션 액션 구현

- FrontEnd/my-car/src/mycar/components/completePage/AnimationMovingCar.js
- FrontEnd/my-car/src/mycar/components/completePage/CompleteTopBanner.js
유저가 색상 선택 페이지에서 선택한 차 이미지로 완성 이미지 나타나게 구현
[issue] #86
> [feat] 내차만들기/완성페이지 차 이미지 수정

- FrontEnd/my-car/src/common/Alert.js
최상단 컴포넌트 Alert 디자인 변경
[issue] #92
> [feat]Alert 디자인 변경

- FrontEnd/my-car/src/mycar/Mycar.js
> [feat] 페이지 상태 url에 따라 반영

- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/components/common/NavBar.js
네비게이션 바 4번 내비 표시 삭제
[issue] #117
> [refactor]네비게이션 바 리팩토링

- FrontEnd/my-car/src/mycar/Mycar.js
useEffect 의존성 배열 사용해서 해결했습니다~~~!
[issue] #123
> [fix] 내차만들기 페이지 이동 버그 수정

- FrontEnd/my-car/src/mycar/components/colorPage/RotateImg.js
- FrontEnd/my-car/src/mycar/routers/Color.js
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/62049151/2bb7b41b-4fdd-46de-aacc-0a81f7f51221
선택된 이미지의 색상에 따라 360도 회전 잘 됩니다!
드래그 속도에 대한 조절은 threshold 값 변경으로 할 수 있습니다.
<br>
**고민해야할 점** 
- (세번째 색상선택 참고)네트워크 상황이나 서버랑 통신하는 과정에서 딜레이가 생기는 것 같아요
- 이미지의 크기가 너무 크다보니 이미지 컨테이너 크기와 비율을 정하는데 어려움이 있었고, 지금도 자연스럽지 않은 것 같아요
[issue] #12
> [FE]360도 회전 이미지 구현

- FrontEnd/my-car/src/mycar/components/common/SummaryModal.js
- FrontEnd/my-car/src/mycar/components/selectOptionPage/DetailExplainCard.js
- FrontEnd/my-car/src/mycar/routers/Color.js
견적 요약 보기 모달에서 스크롤바 스타일이 윈도우 OS에서 확인할 때 이상할 수 있기 때문에 스크롤은 유지하되 스크롤바는 제거했고
딤 블러도 2px -> 6px로 설정해주었습니다~!
> [FE] 견적요약모달 스크롤바 제거 및 딤 블러 세기 증가

- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/main/Main.js
- FrontEnd/my-car/src/mycar/components/completePage/CompletedFunction.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
- FrontEnd/my-car/src/mycar/routers/Model.js
내차만들기 내 완성페이지 setState함수로 인해 여러번 렌더링 되는 문제 해결 및 context 분리했습니다.
[issue] #92
> [FE]완성페이지 setState오류 해결

- FrontEnd/my-car/src/mycar/components/common/TrimImg.js
- FrontEnd/my-car/src/mycar/routers/Color.js
색상페이지 오류 해결 및 내장색상 컨테이너 width 700px로 통일했습니다~
[issue] #132
> [FE]색상 페이지 오류 해결

- FrontEnd/my-car/src/archiving/RootArchiving.js
- FrontEnd/my-car/src/archiving/components/AdditionalInfo.js
- FrontEnd/my-car/src/archiving/components/DetailBanner.js
- FrontEnd/my-car/src/archiving/router/ArchivingDetail.js
- FrontEnd/my-car/src/assets/saveLogo.svg
아카이빙 상세페이지 내 배너 아래 추가 정보 컴포넌트 구현했습니다.
선택옵션으로 되어있는 부분은 데이터 받을 때 전체 리뷰 태그 데이터로 변경할 예정입니다.
> [FE] additional info

- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
리뷰카드 hover 스타일 변경했습니다~
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/1a82d3be-f8b5-44b1-8599-79f499de66a5
[issue] #146
> [FE] 아카이빙/메인 리뷰카드 hover 스타일

- FrontEnd/my-car/src/archiving/components/AdditionalInfo.js
- FrontEnd/my-car/src/archiving/components/DetailBanner.js
- FrontEnd/my-car/src/archiving/components/optDetailCard.js
- FrontEnd/my-car/src/archiving/router/ArchivingDetail.js
- FrontEnd/my-car/src/assets/optionCardDivision.svg
- FrontEnd/my-car/src/common/ChivingHeader.js
api연동 후에 예외처리 할 예정입니다 ~
<br><br>
> [FE] option card

- FrontEnd/my-car/src/archiving/components/AdditionalInfo.js
- FrontEnd/my-car/src/archiving/components/optDetailCard.js
- FrontEnd/my-car/src/archiving/router/ArchivingDetail.js
- FrontEnd/my-car/src/assets/optionCardDivision.svg
(현재 모든 데이터는 더미데이터를 이용하였습니다.)
> - 호버시 색상 변경
> - 선택되었을 시에도 호버 시 색상 변경
> - 전체 카드 중 하나만 선택할 수 있게 설정(선택되어있는 상태에서 다른 카드 선택시 이전 카드 자동 해제)
+ 실제 데이터를 이용해 해 볼 예정이며, 호버 시 이미지 확대도 함께 진행할 예정입니다.
+ 패키지 내 여러 옵션들을 어떻게 보여줘야할지 여전히 고민중입니당....
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/62049151/73d0d8cb-12b5-434e-bfe7-a60f69ac2e65
[issue] #147
> [FE]옵션 카드 호버/선택 시 스타일 변경

- FrontEnd/my-car/src/archiving/RootArchiving.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/context/archiving/ArchivingProvider.js
Archiving.js(아카이빙 메인페이지)에서 context provider로 감싸다보니 아카이빙 상세페이지에서 들어갔다가 
다시 메인페이지로 돌아가니까 context가 초기화 되는 문제가 발생 
RootArchiving.js에서 감싸는 걸로 변경하여 해결
[issue] #166
> [FE] 아카이빙 메인 context 초기화 문제

- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
- FrontEnd/my-car/src/util/DateFomat.js
util 폴더를 새로 생성하여 해당 함수를 넣었습니다! 재사용 해도 될 것 같아요!
```javascript
export function formatDate(dateString) {
const date = new Date(dateString);
const options = { year: '2-digit', month: 'long', day: 'numeric' };
return date.toLocaleDateString('ko-KR', options);
}
```
[issue] #166
> [FE] created_at(서버) 데이터 형식 변경 util 함수 생성 및 적용

- BackEnd/FourEver/build.gradle
> [BE] SpringBootTest 작동 안하는 에러 해결

- .gitignore
- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/api.js
- FrontEnd/my-car/src/archiving/components/Loading.js
- FrontEnd/my-car/src/archiving/hook/useFetch.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/context/archiving/ArchivingProvider.js
- FrontEnd/my-car/src/login/AuthCode.js
- FrontEnd/my-car/src/login/Login.js
- FrontEnd/my-car/src/router.js
인가코드를 통해 서버에 액세스 토큰을 요청하고, 받은 액세스 토큰을 로컬스토리지에 저장하여
다른 API에 접근할 떼 header의 Authorization에 액세스 토큰을 담아 로그인 정보가 유효하면 정상적으로 페이지를 이용할 수 있습니다.
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/66a992ee-c30c-40ac-8fcb-6a9b0b409a9f
[issue] #62
> [FE] 로그인 구현

- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/IntegrationBaseTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/car/api/CarControllerDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/car/application/CarServiceDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/car/repository/CarRepositoryDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/model/api/ModelControllerDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/model/application/ModelServiceDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/model/repository/ModelRepositoryDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/trim/api/TrimControllerDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/trim/application/TrimServiceDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/integration/trim/repository/TrimRepositoryDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/car/api/CarControllerDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/car/application/CarServiceDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/car/dto/CarMapperTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/car/repository/CarRepositoryDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/model/api/ModelControllerDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/model/application/ModelServiceDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/model/dto/ModelMapperTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/model/repository/ModelRepositoryDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/trim/api/TrimControllerDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/trim/application/TrimServiceDefaultImplTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/trim/dto/TrimMapperTest.java
- BackEnd/FourEver/src/test/java/A4/FourEver/domain/unit/trim/repository/TrimRepositoryDefaultImplTest.java
- BackEnd/FourEver/src/test/resources/create.sql
- 시간이 너무 부족하여, 그동안 작업하던 코드 주석 처리 후 저장
- 나중에 이어할지 결정
> [BE] 내 차 만들기 통합 테스트 보류

- FrontEnd/my-car/src/archiving/components/OptSelectionBar.js
- FrontEnd/my-car/src/archiving/components/WarningTooltip.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
- 옵션칩을 5개 이상 선택하려고 할 때 안내 툴팁이 뜨며 선택할 수 없게 하는 기능을 추가했습니다.
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/db4af1d2-4ac2-47bf-83b7-3e742ba72efc
[issue] #190
> [FE] 아카이빙/메인 옵션칩 선택 개수 제한

- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
> [FE] 아카이빙 카드 변경

- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/common/Loading.js
- FrontEnd/my-car/src/login/AuthCode.js
- FrontEnd/my-car/src/mycar/components/common/PageMoveBtns.js
- FrontEnd/my-car/src/mycar/components/completePage/AnimationMovingCar.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
내차만들기 완성페이지에 진입했을 때 유저가 선택한 트림, 옵션 등의 id를 body에 담아 POST 요청 보내는 패치 과정을 구현
[issue] #128
> [FE] 내차만들기 완성페이지 API 연결

- FrontEnd/my-car/src/login/Login.js
- FrontEnd/my-car/src/main/components/MainHeader.js
- 메인 화면 로그아웃 기능 추가 
- "/" 초기 화면에서 jwt 토큰이 유효하다면 바로 로그인 되어있는 상태로 판단 후 "/main"으로 이동합니다.
[issue] #62
> [feat] 로그아웃 및 자동 로그인

- FrontEnd/my-car/src/mycar/components/colorPage/RotateImg.js
- FrontEnd/my-car/src/mycar/routers/Color.js
Promise 이용하여 로딩처리를 진행했습니다.
```javascript
const preloadCarImg = () => {
const promise = CarColor.map((color) => {
return new Promise((resolve) => {
const imagePaths = Array.from(
{ length: 60 },
(_, index) =>
`http://hyundaimycar.store/rotation/${color}/${index + 1}.png`,
);
imagePaths.forEach((path) => {
const img = new Image();
img.src = path;
img.onload = resolve;
});
});
});
return Promise.all(promise);
};
useLayoutEffect(() => {
preloadCarImg().then(() => {
setLoading(false);
});
// eslint-disable-next-line react-hooks/exhaustive-deps
}, []);
```
브라우저 캐시에 이미지가 없을 경우 Promise 를 통해 각각 이미지 다운로드 과정에 promise를 걸어주고, Promise.all을 통해 전달합니다.
이미지를 모두 다운 받은 뒤에 loading을 false처리 해줍니다.
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/bf642d57-5164-433a-a980-cb8fd145caf9
로딩중 화면을 많이 …
> [FE] 내차만들기 360장 이미지 로딩처리

- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/common/Header.js
취소 버튼 눌렀을 때 버그 수정 및 폰트 적용 안됨 관련 오타 해결
[issue] #212
> [FE] 최상단 모달 버그 수정 및 스타일 일부 변경

- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/context/mycar/UserCarProvider.js
- FrontEnd/my-car/src/mycar/UserCarPostAPI.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
API 설정 해놨습니다~ 실제로 아직 연결되진 않습니다
[issue] #15
> [feat] 내차만들기 임시저장

- FrontEnd/my-car/src/login/AuthCode.js
- FrontEnd/my-car/src/login/Login.js
백엔드 요청으로 로그인 관련 요청 서버 url을 변경하였습니다.
[issue] #62
> [fix] 로그인 서버 url 변경

- FrontEnd/my-car/src/assets/removeIcon.svg
- FrontEnd/my-car/src/common/ChivingHeader.js
- FrontEnd/my-car/src/mychiving/Mychiving.js
- FrontEnd/my-car/src/mychiving/RootMychiving.js
- FrontEnd/my-car/src/mychiving/components/CardByMe.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
- FrontEnd/my-car/src/mychiving/router/MychivingDetail.js
- FrontEnd/my-car/src/router.js
카드가 컨테이너 넘어갈 시에는 가로 스크롤로 처리하였습니다.
아직 API연동은 하지 않았습니다 !
> [FE] 마이카이빙 내가 만든 차량목록 카드

- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/mychiving/components/CardByMe.js
- FrontEnd/my-car/src/mychiving/components/DeleteAlert.js
- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
+ 현재 제 노트북에서 폰트 적용이 안되어서 글씨 관련, 줄 넘어가는 것 수정은 월요일에 할 예정입니다!
+ 아직 API 연동은 안된 상태이며 API 연동 후 수정이 필요한 부분 수정할 예정입니다 ~
+ 두번째 경우에서 선택옵션이 여러개일 시 가로 스크롤로 동작되며, 스크롤바는 커스텀예정입니다 !
+ 논의해볼 내용있으시면 알려주세요 !! 의견 언제나 환영입니다 !!!
> [FE] 마이카이빙 모달 생성

- FrontEnd/my-car/src/archiving/RootArchiving.js
- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
- FrontEnd/my-car/src/context/archiving/ArchivingProvider.js
내차만들기 도중 아카이빙으로 이동했을때 유저가 이미 추가한 옵션들을 디폴트로 선택된 상태로 지정해줬습니다!
메인 -> 아카이빙으로 갈 시 디폴트 옵션은 선택되지 않습니다
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/75063380-201f-4cfc-abf4-f64be7d79d70
[issue] #183
> [FE] 내차만들기->아카이빙 디폴트 선택 옵션

- FrontEnd/my-car/src/context/mycar/UserCarProvider.js
- FrontEnd/my-car/src/mycar/UserCarPostAPI.js
- FrontEnd/my-car/src/mycar/routers/Complete.js
내차만들기가 임시저장되는 경우 서버에서 myChiving_id를 받아 로컬스토리지로 저장합니다 
임시저징된 내차만들기 내용이 완성되었을 때 해당 myChiving_id을 서버에 넣어서 전송합니다.
다이렉트로 완성했을 경우 myChiving_id는 0으로 전송합니다. 
[issue] #15
> [FE] 내차만들기 임시저장 & 완료

- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/common/ChivingHeader.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/constant.js
- 최상단 헤더에서 모든 라우터로 이동 가능하도록 네비 버튼을 추가했습니다
- 아키빙 헤더에서 내차만들기 바로가기 버튼을 제거했습니다
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/234cdf0b-a54f-4d80-b955-d30170896af0
[issue] #225
> [FE] 최상단 헤더 네비 버튼 추가 & 카이빙 헤더 내차만들기 버튼 제거

- FrontEnd/my-car/src/mycar/UserCarPostAPI.js
myChiving_id -> id로 name 변경합니다
[issue] #15
> [FE] UserCArPostAPI body field name 변경

- FrontEnd/my-car/src/archiving/components/AdditionalInfo.js
is_save 데이터로 저장 버튼 상태를 초기화 한 뒤
버튼을 클릭할 때 마다 리뷰 삭제 or 저장하는 기능입니다! API 연동 완료했습니다
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/f64918ab-ade5-4c0d-bad1-3e283026923a
[issue] #230
> [FE] 아카이빙/상세 내 피드(마이카이빙)에 리뷰 저장

- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mycar/components/common/ToolTip.js
- FrontEnd/my-car/src/mychiving/components/CardByMe.js
- FrontEnd/my-car/src/mychiving/components/DeleteAlert.js
- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
- FrontEnd/my-car/src/mychiving/hook/useDelete.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
- FrontEnd/my-car/src/router.js
**마이카이빙 내 내가만든 차량 목록 데이터 연결을 완료했습니다.**
**임시저장된 카드에서 +버튼을 누를 시 선택옵션 모달이 보여지게 됩니다.**
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/62049151/139d8c71-8895-47c2-8762-0fac1f4840fe     
**선택 옵션이 없을 시 아래와 같이 보여집니다.**
**x버튼을 누를 시 서버에 DELETE요청을 하게 되며, 삭제 후 즉시 리렌더링 됩니다.**
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/62049151/8696afb1-b547-45cc-8f7c-52f4698adfc4
> [FE] 마이카이빙-내가 만든 차량 목록

- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
[issue] #209
이전 PR에 커밋내용이 들어가지않아 PR다시 올립니다.
> [FE] 선택옵션 예외처리

- FrontEnd/my-car/src/archiving/components/OptReviewHeader.js
- FrontEnd/my-car/src/archiving/components/OptSelectionBar.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/common/ChivingHeader.js
- FrontEnd/my-car/src/common/Loading.js
- 스타일 변경했습니다!
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/013ff08a-009a-4786-9f1e-4c9bdbf6b550
[issue] #235
> [FE] 아카이빙 옵션바&필터탭 헤더 스타일 변경

- FrontEnd/my-car/src/archiving/components/OptSelectionBar.js
- FrontEnd/my-car/src/archiving/components/WarningTooltip.js
- FrontEnd/my-car/src/archiving/router/ArchivingDetail.js
- FrontEnd/my-car/src/common/ChivingHeader.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
> [FE] 카이빙 스타일 수정

- FrontEnd/my-car/src/mychiving/components/CardByArchiving.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
스타일 관련 부분은 16인치 맥북으로 고칠 예정입니다!
> [FE] 마이카이빙 뷰

- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/dto/CarReviewMapper.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/dto/CarReviewResultSortedDTO.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/repository/CarReviewRepositoryDefaultImpl.java
- reviews/result 에서 반환하는 데이터 감소.
> [BE] 너무 많은 결과를 한번에 반환하기에 AWS가 뻗어버리는 현상 해결

- FrontEnd/my-car/src/archiving/components/AdditionalInfo.js
- FrontEnd/my-car/src/archiving/components/DetailBanner.js
- FrontEnd/my-car/src/context/archiving/ArchivingProvider.js
- FrontEnd/my-car/src/context/mycar/UserCarProvider.js
- FrontEnd/my-car/src/mycar/Mycar.js
아카이빙 상세페이지에서 이 차량으로 내 차 만들기 버튼 클릭 시 내차만들기 상태를 초기화해주는 데이터에 대한 API 호출 후
받은 데이터를 기반으로 내차만들기 페이지로 이동 후 userCar 상태를 초기화 합니다.
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/4d59cd72-2033-4d10-a855-2563a0afb038
[issue] #243
> [FE] 아카이빙/이 차량으로 내차만들기

- FrontEnd/my-car/src/api.js
- FrontEnd/my-car/src/archiving/components/Onboarding.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/router.js
온보딩 모달 2페이지 API 연결까지 완료했습니다!
모달 등장시 화면 전체 스크롤도 막아놨습니다
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/101038390/fdbdc4c2-079f-4361-8dc6-b4cf92b17116
[issue] #239
> [FE] 아카이빙/온보딩 API 연결

- FrontEnd/my-car/src/archiving/components/AdditionalInfo.js
- FrontEnd/my-car/src/context/mycar/UserCarProvider.js
- FrontEnd/my-car/src/mycar/Mycar.js
- FrontEnd/my-car/src/mychiving/components/CardByMe.js
- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
- 마이카이빙에서 임시저장된 카드를 클릭하고, 나타나는 모달에서 내차만들기 이동하기 버튼을 클릭하면 내차만들기로 해당 데이터를 가지고 이동합니다.
- 잘 작동하는 것을 확인했고(아마요...) 녹화하려고 한 찰나에 서버가 터져서 녹화는 못했습니다
[issue] #243
> [FE] 마이카이빙-내차만들기 이동

- FrontEnd/my-car/src/constant.js
- FrontEnd/my-car/src/mychiving/components/CardByArchiving.js
- FrontEnd/my-car/src/mychiving/components/CardByMe.js
- FrontEnd/my-car/src/mychiving/components/DeleteAlert.js
- FrontEnd/my-car/src/mychiving/hook/useDelete.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
- FrontEnd/my-car/src/mychiving/router/MychivingDetail.js
내가 만든 차량 목록을 삭제 시 사용하고 있는 Alert와 서버로 보내는 DELETE요청을 재사용 하였습니다.
https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/62049151/d2b5d312-36a7-4901-9f2b-16cb40a8c6d5
> [FE] 피드에서 저장한 차량 목록 삭제 API 연결

- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/mycar/components/common/Footer.js
- FrontEnd/my-car/src/mycar/components/common/ImgSelect.js
- FrontEnd/my-car/src/mycar/components/common/TrimImg.js
- FrontEnd/my-car/src/mycar/components/completePage/AnimationMovingCar.js
- FrontEnd/my-car/src/mycar/components/completePage/CompleteTopBanner.js
- FrontEnd/my-car/src/mycar/components/completePage/CompletedFunction.js
- FrontEnd/my-car/src/mycar/components/completePage/FunctionBanner.js
- FrontEnd/my-car/src/mycar/components/selectOptionPage/OptionImage.js
- FrontEnd/my-car/src/mycar/components/trimPage/TrimModelImg.js
- FrontEnd/my-car/src/mychiving/components/CardByMe.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
이미지  border-radius 설정, footer 내 견적요약보기 호버시 스타일 설정
[issue] #261
> [FE] 내차만들기 디자인 리팩토링

- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/common/Header.js
- 엉뚱한 페이지로 이동하는 버그 수정했습니다.
[issue] #250
> [FE] 최상단 헤더 네비버튼 로직 버그 수정

- FrontEnd/my-car/src/context/mycar/UserCarProvider.js
- FrontEnd/my-car/src/mychiving/hook/useDelete.js
- 마이카이빙-> 내차만들기 관련 셋팅을 변경했습니다
- 마이카이빙 내가 만든 차량 목록 삭제 관련 버그를 수정했습니다
[issue] #243
> [FE] 마이카이빙 버그 수정 및 내차만들기 이동 셋팅 변경

- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
- FrontEnd/my-car/src/mychiving/components/CardByArchiving.js
- FrontEnd/my-car/src/mychiving/components/MyCardOrigin.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
디자인 부분은 전체 디자인 리팩토링 브랜치에서 진행할 예정입니다.
> [FE] 마이카이빙 리메이크

- FrontEnd/my-car/src/api.js
- FrontEnd/my-car/src/archiving/components/OptReviewCard.js
- FrontEnd/my-car/src/archiving/components/OptSelectionBar.js
- FrontEnd/my-car/src/archiving/hook/useFetch.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/common/Alert.js
- FrontEnd/my-car/src/context/archiving/ArchivingProvider.js
- FrontEnd/my-car/src/context/mycar/color/ColorPrivider.js
- FrontEnd/my-car/src/mycar/UserCarPostAPI.js
- FrontEnd/my-car/src/mycar/routers/Color.js
- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
- FrontEnd/my-car/src/mychiving/hook/useDelete.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
마지막으로 전체적으로 생기는 버그를 수정했습니다
[issue] #278
> [fix] 전체적인 버그 수정

- FrontEnd/my-car/src/Root.js
- FrontEnd/my-car/src/archiving/router/Archiving.js
- FrontEnd/my-car/src/common/ChivingHeader.js
- FrontEnd/my-car/src/common/Header.js
- FrontEnd/my-car/src/common/ScrollToTop.js
- FrontEnd/my-car/src/mycar/components/colorPage/RotateImg.js
- FrontEnd/my-car/src/mycar/components/common/Footer.js
- FrontEnd/my-car/src/mycar/components/common/SummaryModal.js
- FrontEnd/my-car/src/mycar/components/selectOptionPage/DetailExplainCard.js
- FrontEnd/my-car/src/mycar/components/selectOptionPage/OptionTabs.js
- FrontEnd/my-car/src/mycar/components/trimPage/TrimCard.js
- FrontEnd/my-car/src/mychiving/components/CardByArchiving.js
- FrontEnd/my-car/src/mychiving/components/MyCardOrigin.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
- FrontEnd/my-car/src/style/globalStyle.js
전체적인 스타일 리팩토링을 진행하였습니다.
(스크롤바 커스텀, padding, margin 값 맞추기, 스타일 통일 등)
> [style] 전체적인 스타일 리팩토링

- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/repository/CarRepositoryDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/repository/CarReviewRepositoryDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/model/repository/ModelRepositoryDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/global/config/AuthConfig.java
- 데이터가 많은 테이블을 조회해야 하는 경우 with 안에 limit를 사용하는 것으로 성능 향상
- with문이 메모리를 사용하므로, 위와 같은 경우를 제외한 쿼리는 with 사용하지 않는 것으로 수정
> [BE] 쿼리 최적화

- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/api/CarController.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/application/CarService.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/application/CarServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/repository/CarRepository.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/repository/CarRepositoryDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/api/CarReviewController.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/application/CarReviewService.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/application/CarReviewServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/carReview/repository/CarReviewRepository.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/model/application/ModelServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/model/repository/ModelRepository.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/myChiving/api/MyChivingController.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/myChiving/application/MyChivingService.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/myChiving/application/MyChivingServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/myChiving/repository/MyChivingRepository.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/myChiving/repository/MyChivingRepositoryDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/trim/trim/application/TrimServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/trim/trim/repository/TrimRepository.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/api/UserController.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/api/UserControllerDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/application/UserService.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/application/UserServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/application/auth/AuthService.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/application/auth/AuthServiceDefaultImpl.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/application/auth/JwtProvider.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/application/auth/PasswordUtil.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/repository/UserRepository.java
- BackEnd/FourEver/src/main/java/A4/FourEver/domain/user/repository/UserRepositoryDefaultImpl.java
> [BE] 각 클래스에서 컨벤션에 따른 수정

- BackEnd/FourEver/src/main/java/A4/FourEver/domain/car/repository/CarRepositoryDefaultImpl.java
> [BE] CarRepositoryDefaultImpl 에서 DB 인덱싱에 앞서 쿼리 수정

- FrontEnd/my-car/src/archiving/components/OptSelectionBar.js
> [FE] 아카이빙 수정

- FrontEnd/my-car/src/archiving/components/OptSelectionBar.js
> [fix] 아카이빙 선택바 스타일 수정

- FrontEnd/my-car/src/api.js
- FrontEnd/my-car/src/main/Main.js
- FrontEnd/my-car/src/main/components/MainHeader.js
- FrontEnd/my-car/src/mychiving/router/Mychiving.js
> [FE] 로그아웃 시 관련 버그 수정

- FrontEnd/my-car/src/mychiving/components/DeleteAlert.js
- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
- 마이카이빙 모달 해제 후 스크롤 막힘 문제를 해결하였습니다
> [FE] 마이카이빙 스크롤 막힘문제 해결

- BackEnd/FourEver/src/main/java/A4/FourEver/global/config/AuthConfig.java
- intercepter 상의 설정에서 알맞은 URL로 수정
> [BE] URL 수정으로 인해 발생하는 intercepter 설정으로 인한 에러 해결

- FrontEnd/my-car/src/mycar/routers/Engine.js
- 이전페이지에서 360이미지를 다운받느라, 해당 페이지에서 나타나야하는 이미지 로딩이 느려짐 문제 해결
> [FE] 360 프리로딩 딜레이 수정

- FrontEnd/my-car/src/archiving/components/DetailBanner.js
- FrontEnd/my-car/src/mychiving/components/OptDetailModal.js
마이카이빙 배너에 시승/구매 데이터가 표시되는 부분을 예외처리 하였습니다.
[issue] #278
> [FE] 마이카이빙 배너 수정
